.gitignore
app/package-lock.json
app/package.json
app/plugins/sqlite.ts

Sql gets initialized in the sqlite.ts file. A database object is now added to the fastify object.
The .git_keep file is just to be able to push the database dir.
Have fun!!

add sql initialization

---

app/Dockerfile
docker-compose.yml

- Update Dockerfile context and container name
- Add volume configuration for Node.js development

Update docker-compose for Node.js app development

---

app/plugins/sqlite.ts
app/services/database/migrations/001_users_create.sql
app/services/database/migrations/002_users_blocked_create.sql
app/services/database/migrations/003_users_friends_create.sql
app/services/database/migrations/004_messages_create.sql
app/services/database/migrations/005_turnaments_create.sql
app/services/database/migrations/006_matches_create.sql
app/services/database/migrations/007_r_users_matches.sql
app/services/database/migrations/008_r_users_tournament_create.sql

Migration scripts are added that will check the existence of all needed tables and create them if they don't exist. 
A table for global chat messages nees to be added, please DON'T DELETE branch!

add migrations and call them in sqlute hook before start

---

app/plugins/sqlite.ts
app/services/friends/doesUserExist.ts

Sorry, it's fixed now.
Modify the return of the doesUserExist function to fetch the user, check if a valid ID was retrieved, and return true or false to ensure a boolean is returned. Also compiles! ;)

Add a check for the fetched user ID and return true or false

---

app/public/ts/friends.ts
app/routes/users/index.ts
app/templates/components/button.hbs
app/templates/components/user/blockbutton.hbs
app/templates/components/user/card.hbs
app/templates/helpers/index.ts
app/templates/views/profile.hbs
app/templates/views/user.hbs

this adds profiles and has the friend/block buttons etc. block functionality is not yet there

78 user profiles

---

app/services/games/lobby/Lobby.ts
app/services/games/lobby/start/canLobbyBeStartedCheck.ts
app/services/games/lobby/start/startLobbyHandler.ts

add feature that correctly checks if lobby can be started: 
Endpoint start does not change.

50 add lobby

---

app/.env.example
app/app.ts
app/middlewares/auth.ts

- Introduced DEV_MODE variable in .env.example and app.ts for environment configuration.
- Updated authentication middleware to handle user existence checks and image saving in development mode.

Add DEV_MODE configuration and enhance authentication middleware

---

app/assets/app.css
app/package.json
app/routes/games/lobby/join/joinLobby.ts
app/routes/play/index.ts
app/routes/play/join/code/index.ts
app/services/games/lobby/Lobby.ts
app/services/games/lobby/getters/getLobbyById.ts
app/services/games/lobby/getters/getPublicLobbys.ts
app/services/games/lobby/join/joinLobbyHandler.ts
app/services/games/lobby/lobbyVaidation/isUserInAnyLobby.ts
app/services/games/lobby/new/newLobbyHandler.ts
app/templates/components/button.hbs
app/templates/components/game/lobby.hbs
app/templates/components/lobby/lobby.hbs
app/templates/components/lobby/user.hbs
app/templates/helpers/index.ts
app/templates/views/home.hbs
app/templates/views/lobby/code.hbs
app/templates/views/lobby/page.hbs
app/templates/views/play.hbs

adds `/play` page aswell as the lobby view with the abbility to join, leave and start. to test lobbys there are some dummy lobbies created in dev mode. 
closes #101 
closes #84

add play page 

---

app/interfaces/games/lobby/GameSettings.ts
app/public/ts/lobby.ts
app/public/ts/pong.ts
app/public/ts/router.ts
app/services/games/lobby/new/newLobbyHandler.ts
app/services/games/lobby/start/addGameToDatabase.ts
app/services/games/lobby/start/startLobbyHandler.ts
app/templates/views/game/pong.hbs

adds the game page and basic playing capabilities. needs to be improved on once the frontend knows who is who

106 pong game page

---

app/app.ts
app/package-lock.json
app/package.json

add fastify/swagger which gives a ui for endpoints. nice for testing and evals. available at `localhost:3000/documentation`

install fastify swagger

---

app/services/games/gameHandler/isUserInGame.ts

Two functions have been added:
isUserInGame: gameId | undefiened (Path: /games/gameHandler/isUserInGame.ts)
isUserInAnyLobby: lobbyId | null (Path: games/lobby/lobbyVaidation/isUserInAnyLobby.ts)
Wil be added later:
isInTournamet: tournamentId | undefiened (after tournament got implemented)

add new function to check if a user is in a game

---

app/public/ts/lobby.ts
app/templates/views/lobby/page.hbs

show user the error if start fails because of missing ws for other player. also reload page is ws error to force reconnect

fix: no feedback on lobby start error

---

app/plugins/error.ts
app/public/ts/lobby.ts
app/templates/views/lobby/page.hbs
app/types/games/lobby/MinAndMaxPlayers.ts

addAiOpponent Button

---

app/services/games/gameHandler/GameManager.ts
app/services/games/gameHandler/terminateGame.ts

Once the game is done all players will be disconnected from the ws and the gameManger will be removed from the map (the object that holds all games)

add game termination once game is over

---

app/routes/play/game/index.ts
app/services/games/gameHandler/gameWebsocketHandler.ts

If you connect to the game Websocket with an invalid uuid you get the error message and disconnected from the websocket.

add disconnection for invald game websocket connection

---

app/services/games/gameHandler/GameManager.ts
app/services/games/lobby/Lobby.ts
app/services/games/lobby/start/gameManagerCreate.ts
app/services/games/matchMaking/createMatch.ts
app/types/games/gameHandler/GameOrigin.ts

Now a new function is added that handles the next step after a game is over. Later also the Tournament will be handled in there.

create new functionality that opens the lobby once game is over

---

app/services/games/modifierManager.ts
app/services/games/pong/pong.ts

Not sure how to recreate the crash to see if it's fixed, so i mainly added simple 'fail-safe' in case the snapshot doesn't have the required data + 1 initial empty tick to make it at least not crash.

213 crash on game start

---

app/public/pong.html
app/services/games/modifierBase.ts
app/services/games/modifierManager.ts
app/services/games/pong/gameModifiers/goalReset.ts
app/services/games/pong/pong.ts
app/services/games/pong/powerUps/blinkingBall.ts
app/services/games/pong/powerUps/bumper.ts
app/services/games/pong/powerUps/multiBall.ts
app/services/games/pong/powerUps/shooter.ts
app/services/games/pong/powerUps/speedBoost.ts

Should also fix #243 (ball speed is reset but was overwritten by a powerUp that didn't reset correctly)

Fixed powerUp not being removed correctly onGoal (-> onBallReset)

---

app/services/games/gameBase.ts
app/services/games/gameHandler/aiLoop.ts

A new check in the ai loop is added to check if the ai is not eliminated.

update just not eliminated ais in aiLoop

---

app/config.ts
app/gameRegistry.json
app/interfaces/games/lobby/GameSettings.ts
app/services/games/modifierBase.ts
app/services/games/pong/gameModes/classicPong.ts
app/services/games/pong/gameModifiers/idleWallBounceAcceleration.ts
app/services/games/pong/gameModifiers/paceBreaker.ts
app/services/games/pong/pong.ts
app/services/games/pong/pongAIOpponent.ts
app/services/games/pong/powerUps/bumper.ts
app/services/games/pong/powerUps/shooter.ts
app/services/games/pong/powerUps/speedBoost.ts

#265 modifiers mini rework

---

app/routes/games/tournament/leave/leaveTournament.ts
app/services/games/tournament/start/startTournamentHandler.ts

Prevent the tournament from being started twice.

Add a new check in the tournament handler

---

app/client/chat.ts
app/client/router.ts

fix that invite button is still there even when navigation to..

---

app/client/chat.ts
app/client/router.ts
app/routes/games/lobby/invite.ts
app/routes/games/tournament/invite.ts
app/services/chat/live.ts
app/services/games/lobby/lobbyWebsocket/getLobby.ts

tournament chat invites

---

compose-prod/docker-compose.yml
compose-prod/nginx.conf

Includes nginx service with self-signed cert generation and config for HTTPS termination and proxying to the app container. Adjusts app healthcheck and updates service indentation for consistency.

Add NGINX reverse proxy with SSL to production compose setup

---

app/services/games/gameHandler/GameManager.ts

Lets go back to the basics and explore the difference between & and ||.

switch and to or operators in shuffle check

---

app/client/pong.ts
app/config.ts
app/services/games/modifierManager.ts
app/services/games/pong/pong.ts
app/services/games/pong/powerUps/bumper.ts
app/services/games/pong/powerUps/bumperShield.ts
app/services/games/pong/powerUps/portals.ts
app/services/games/pong/powerUps/protectedPowerUp.ts
app/services/games/pong/powerUps/speedGate.ts
app/types/games/pong/gameState.ts

Speed gate rotation in 1v1
SpeedBoost fix
Visual Clarity patch (on portal/bumper walls)

333 game speedgate rotation in 1v1

---

app/services/games/gameHandler/leaveGame/leaveGameHandler.ts
app/services/games/tournament/join/joinTournamentHandler.ts

in case no error -> removes player from game before redirection

redirect anyways (error thrown or not) 

---

app/config.ts
app/gameRegistry.json
app/services/games/modifierManager.ts
app/services/games/pong/gameModifiers/powerUpSpawner.ts
app/services/games/pong/powerUps/bumper.ts

366 config game config updates
